import React from 'react'

export default function AIInsightsCard({ aiInsights }) {
  if (!aiInsights || !aiInsights.trim()) return null

  return (
    <div className="mp-card" style={{ padding: '16px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}>
        <p className="mp-label">AI Insights</p>
        <span style={{
          fontSize: '9px',
          fontWeight: 600,
          padding: '2px 8px',
          borderRadius: '20px',
          background: 'rgba(5,150,105,0.08)',
          color: '#059669',
          letterSpacing: '0.04em',
          border: '0.5px solid rgba(5,150,105,0.20)',
        }}>
          Generated by AI
        </span>
      </div>
      <p style={{ fontSize: '13px', color: 'var(--mp-text)', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>
        {aiInsights}
      </p>
    </div>
  )
}
